# Ansible playbook AWS - install docker (2021)
- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_only: yes
- name: Ensure a list of yum packages are installed
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - python-pip
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - docker

- name: install python3, ansible and docker
  shell: |
    yum install python3-pip
    pip3 install ansible
    pip3 install docker-py
    systemctl start docker
    systemctl enable docker